basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
  path('', views.basket_summary, name='basket_summary'),
  path('add/', views.basket_add, name='basket_add'),
  path('delete/', views.basket_delete, name='basket_delete'),
  path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls',namespace='store')),
    path('basket/', include('basket.urls',namespace='basket')),
    path('account/', include('account.urls',namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import include, path

from . import views

#we need this for 'store:name' thats mean in store url and run given name path 
app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


# Create your models here.
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
    

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'
    
    #verilen apptaki url e git mevcut argumani urldeki yerine koy ve bir url elde et
    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug]) 

    def __str__(self):
        return self.name

# https://stackoverflow.com/questions/38388423/what-does-on-delete-do-on-django-models


class Product(models.Model):

    category = models.ForeignKey(
        Category, related_name='product', on_delete=models.CASCADE)  # her urun bir kategoriye ihtiyac duyar.

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='product_creator', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/' , default='images/MoonlightScluptor.jpg')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)
    
    #verilen apptaki url e git mevcut argumani urldeki yerine koy ve bir url elde et
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug]) 

    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products':products})

def product_detail(request,slug):
    product  = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request,'store/products/single.html', {'product':product})

def category_list(request,category_slug):
    category  = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request,'store/products/category.html', {'category':category,'products':products})

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}
{% block title %}
  MangaBazaar
{% endblock title %}

{% block content %}

<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">{{category.name|title}}</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ product.image.url }}" role="img" aria-label="Placeholder: Thumbnail" 
            preserveAspectRatio="xMidYMid slice" focusable="false">
          
            <div class="card-body">
              <p class="card-text">
                <a class="text-blue text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
           
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>


</main>


{% endblock content %}

templates/store/products/single.html
{% extends "../base.html" %}
{% load static  %}
{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
              <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ product.image.url }}" role="img" aria-label="Placeholder: Thumbnail" 
              preserveAspectRatio="xMidYMid slice" focusable="false">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Tutar</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.price }} tl</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Adet</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
                            <button type="button" id="add-button" value="{{product.id}}" class="btn btn-secondary btn-sm">Sepete
                                    Ekle</button>
                                    <button type="button" id="add-button" value="{{product.id}}" class="btn btn-light fw500">Favorilere 
                                    Ekle</button>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

</div>

<script>
       $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}